SRCS		=	main.cpp A.Class.cpp B.Class.cpp C.Class.cpp Base.Class.cpp
OBJS		=	$(SRCS:%.cpp=%.o)

NAME		=	Dynamic

CC					=	g++
CFLAGS				=	-Wshadow -Wall -Wextra -Werror -fsanitize=address -std=c++98\

all:		$(NAME)

$(NAME):	${OBJS}
				${CC} ${CFLAGS} ${OBJS} -o ${NAME}

clean:
				@rm -f ${OBJS}

fclean:		clean
				@rm -f $(NAME)

re:			fclean all

.PHONY:		all clean fclean re